version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./user-management:/app/user-management
    ports:
      - '3000:3000'
    stdin_open: true
