version: '3.9'
services:
  app:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd user-management && npm run start'
    ports:
      - 3000:3000
    tty: true
